name: nyc_taxi_data_pipeline
version: 1.0.0
profile: nyc_taxi_data_pipeline

model-paths: ["models"]
#seed-paths: ["seeds"]
test-paths: ["tests"]
#analysis-paths: ["analysis"]
macro-paths: ["macros"]
#snapshot-paths: ["snapshots"]

models:
  nyc_taxi_data_pipeline:
    +materialized: view
    bronzes:
      schema: bronze
    silvers:
      schema: silver
    golds:
      schema: gold
