name: nyc_taxi_data_pipeline
version: 1.0.0
profile: nyc_taxi_data_pipeline

model-paths: ["models"]
#seed-paths: ["seeds"]
#test-paths: ["tests"]
#analysis-paths: ["analysis"]
macro-paths: ["macros"]
#snapshot-paths: ["snapshots"]

models:
  nyc_taxi_data_pipeline:
    +file_format: delta

    bronzes:
      +tags: ['bronze']
      +materialized: view
      schema: bronze
    silvers:
      +tags: ['silver']
      +materialized: incremental
      schema: silver
    golds:
      +tags: ['gold']
      +materialized: table
      schema: gold

seeds:
  nyc_taxi_data_pipeline:
    schema: mock_tables

vars:
  unit_test: false
  mock_schema: mock
