nyc_taxi_data_pipeline:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      host: spark-thrift
      port: 10000
      schema: default
      connect_timeout: 60
      threads: 3
