version: 2

sources:
  - name: bronze
    schema: bronze
    tables:
      - name: yellow_trip_data
        loaded_at_field: processing_time
        freshness:
          warn_after: { count: 2, period: day }
          error_after: { count: 3, period: day }
      - name: green_trip_data
        loaded_at_field: processing_time
        freshness:
          warn_after: { count: 2, period: day }
          error_after: { count: 3, period: day }
      - name: fhv_trip_data
        loaded_at_field: processing_time
        freshness:
          warn_after: { count: 2, period: day }
          error_after: { count: 3, period: day }
      - name: taxi_trip_zones

  - name: mock
    schema: mock_tables
    tables:
      - name: input_fhv_trips_data
      - name: yellow_trip_data
      - name: green_trip_data
      - name: fhv_trip_data
