version: 2

sources:
  - name: bronze
    schema: bronze
    tables:
      - name: yellow_trip_data
      - name: green_trip_data
      - name: fhv_trip_data
  - name: mock
    schema: mock_tables
    tables:
      - name: input_fhv_trips_data
      - name: yellow_trip_data
      - name: green_trip_data
      - name: fhv_trip_data
